files_to_sync:
  - src:
      - ".packit.yaml"
      - "build/package/rpm/go-fdo-client.spec"
    dest: .

upstream_package_name: go-fdo-client
downstream_package_name: go-fdo-client

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
  - make
  - git
  - golang
  - tar

packages:
  go-fdo-client-fedora:
    downstream_package_name: go-fdo-client
    upstream_package_name: go-fdo-client
    specfile_path: build/package/rpm/go-fdo-client.spec
  go-fdo-client-centos:
    downstream_package_name: go-fdo-client
    upstream_package_name: go-fdo-client
    specfile_path: build/package/rpm/go-fdo-client.spec
    pkg_tool: centpkg

actions:
  fix-spec-file:
    - bash -c 'sed -i "s/^%global commit .*/%global commit          $(git rev-parse HEAD)/;" build/package/rpm/go-fdo-client.spec'
  create-archive:
    - make packit-create-archive

jobs:
  - &copr_fedora
    job: copr_build
    packages: [go-fdo-client-fedora]
    trigger: pull_request
    targets:
      - fedora-stable
      - fedora-development

  - <<: *copr_fedora
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

  - job: propose_downstream
    trigger: release
    packages: [go-fdo-client-fedora]
    dist_git_branches:
      - fedora-stable
      - fedora-development

  - &copr_centos
    job: copr_build
    packages: [go-fdo-client-centos]
    trigger: pull_request
    targets:
      - centos-stream-10

  - <<: *copr_centos
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

  - job: tests
    trigger: pull_request
    identifier: e2e-fedora
    fmf_path: test/fmf
    tmt_plan: plans/e2e
    packages: [go-fdo-client-fedora]
    targets:
      - fedora-stable
      - fedora-development

  - job: tests
    trigger: pull_request
    identifier: e2e-centos
    fmf_path: test/fmf
    tmt_plan: plans/e2e
    packages: [go-fdo-client-centos]
    targets:
      - centos-stream-10

