files_to_sync:
  - src:
      - ".packit.yaml"
      - "build/package/rpm/go-fdo-client.spec"
      - "build/package/rpm/go-vendor-tools.toml"
      - "build/package/rpm/go-fdo-client-*-vendor.tar.gz"
    dest: .

upstream_package_name: go-fdo-client
downstream_package_name: go-fdo-client

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
  - make
  - git
  - golang
  - bison
  - go-vendor-tools
  - gzip
  - tar
  - python3-tomlkit

packages:
  go-fdo-client-fedora:
    downstream_package_name: go-fdo-client
    upstream_package_name: go-fdo-client
    specfile_path: build/package/rpm/go-fdo-client.spec
  go-fdo-client-centos:
    downstream_package_name: go-fdo-client
    upstream_package_name: go-fdo-client
    specfile_path: build/package/rpm/go-fdo-client.spec
    pkg_tool: centpkg

actions:
  post-upstream-clone:
    - |
      bash -c "
      #! /bin/bash
      set -x
      go_version=$(go version | cut -f 3 -d ' ')
      if [ "${go_version}" != "go1.25.0" ]; then
        command -v gvm &>/dev/null || { curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/refs/tags/1.0.22/binscripts/gvm-installer -o /tmp/gvm-installer && bash /tmp/gvm-installer; }
        source ${HOME}/.gvm/scripts/gvm
        gvm install go1.25.0
        gvm use go1.25.0 --default
      fi
      "
  pre-sync:
    - make vendor-tarball VERSION=${PACKIT_PROJECT_VERSION}
  create-archive:
    - make packit-create-archive VERSION=${PACKIT_PROJECT_VERSION}

jobs:
  - &copr_fedora
    job: copr_build
    packages: [go-fdo-client-fedora]
    trigger: pull_request
    targets:
      fedora-branched:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/fedora-$releasever-$basearch/
        additional_packages:
          - golang
      fedora-rawhide:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/fedora-rawhide-$basearch/
        additional_packages:
          - golang

  - <<: *copr_fedora
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

  - job: propose_downstream
    trigger: release
    packages: [go-fdo-client-fedora]
    dist_git_branches:
      - fedora-stable
      - fedora-development

  - &copr_centos
    job: copr_build
    packages: [go-fdo-client-centos]
    trigger: pull_request
    targets:
      epel-9:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/epel-9-$basearch/
        additional_packages:
          - golang
      epel-10:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/epel-10-$basearch/
        additional_packages:
          - golang

  - <<: *copr_centos
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

