include:
  - networks.yaml
services:
  manufacturer:
    container_name: manufacturer
    hostname: manufacturer
    image: manufacturer
    build: https://github.com/fido-device-onboard/go-fdo-server.git#${GO_FDO_SERVER_BRANCH:-main}
    environment:
      TZ: Europe/Madrid
    ports:
      - 8038:8038
    command: --db=/tmp/sqlite.db --db-pass '2=,%95QF<uTLLHt' --debug serve manufacturer:8038
    networks:
      - fdo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://manufacturer:8038/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  rendezvous:
    container_name: rendezvous
    hostname: rendezvous
    image: rendezvous
    build: https://github.com/fido-device-onboard/go-fdo-server.git#${GO_FDO_SERVER_BRANCH:-main}
    environment:
      TZ: Europe/Madrid
    ports:
      - 8041:8041
    command: --db=/tmp/sqlite.db --db-pass '2=,%95QF<uTLLHt' --debug serve rendezvous:8041
    networks:
      - fdo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://rendezvous:8041/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s


  owner:
    container_name: owner
    hostname: owner
    image: owner
    build: https://github.com/fido-device-onboard/go-fdo-server.git#${GO_FDO_SERVER_BRANCH:-main}
    environment:
      TZ: Europe/Madrid
    ports:
      - 8043:8043
    command: --db=/tmp/sqlite.db --db-pass '2=,%95QF<uTLLHt' --debug serve owner:8043
    networks:
      - fdo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://owner:8043/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
