name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go:
    name: Test Go packages
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
